language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: C3OBxMw5XVOGmzZC+l+GzwLY5SrL0Zps9kUHqnoEzjP2Pz6bDJkJwRNutQWwkbPhjxG0BbQR8HIZGRDQFFNybMAVI5flDUNKcERzzUvjJW0y41COvSMShWwdMQYCfD7oVMW0fYujRgUVEJx1Fze7rGJpqInzyZaEaB2M75hUUuyYc4xUHpt6nDdHx1u+TohfsgNnwJoAYLzLj4dYAuEd4upPz5tS+3dX7hiUbgi8BWpSyf72FoVbdoh4d3xA3f0Qw5IINkfbSRBCBRwcR31mxVf2HlkG1Fivlm1UNE9aAGZMLeS/TZoNMYlEHQc1vhbZpEyD95UL8iRptmuEgqf0ilRm7a/lyJZGIjzHU5gnSMiV0FPcsn0X38oDhWjMaB2XircO7L0sz8+ILaONfMzZ3HqhEgUCpc6fDkLpIdCorCMQvtDFG7PEwnew2ajq/QSh0EyWmrYMM3NGmwMV3HjmjU7t/gyzgZZtGPRi57ucpcaBxy9ypneJU8PyDMjIvHE391IOmOVKVi7KXZGS2bdVA3BkX60cjqRn90jmhVcm4a90JdKMvTirIz9eTkGVtdju6XyhwsdWFE17Zr8Lfi+DvxRn/Z7k62pxuW4H0wGB6pofIR8yBWhUWM9LN8zNN7VHf1z7VUquSOtYW+rw2v6ZwV6BRfMFA2k+P16QYIxypX4=
  app: pure-inlet-71931
  on:
    repo: bradleymarch/beerboss
